[[contracts]]
fqn = "casper_swap::LockVault"

[[contracts]]
fqn = "casper_swap::BridgeController"

[[contracts]]
fqn = "casper_swap::RelayerRegistry"

[[contracts]]
fqn = "casper_swap::SwapRouter"
